id: elasticsearch
version: 1.0.0
config-groups:
  default:
    server:
      label: Elasticsearch server
      mandatory: true
      type: single
      default: 'http://localhost:9200'
      visible: true
      validator: '[A-z0-9\._]+'
      help: 'Specify the Elasticsearch server using the http[s]://[username]:[password]@host:port format'
    index:
      label: The index to send data to
      mandatory: true
      type: single
      default: 'default'
      visible: true
      validator: '[A-z\._]+'
      help: This is just a testing parameter
    type:
      label: The type of document for Elasticsearch
      mandatory: true
      type: single
      default: 'default'
      visible: true
      validator: '[A-z\._]+'
      help: The type of document for elasticsearch
    batch:
      label: Maximum batch size
      mandatory: true
      type: single
      default: 10
      visible: true
      validator: '[0-9]+'
      help: The maximum number of events to batch
    is_aws:
      label: Is the Elasticsearch server in AWS?
      mandatory: true
      type: single
      default: true
      visible: true
      validator: 'true|false'
      help: Whether the Elasticsearch cluster we want to connect to is in AWS or not
    batch:
      label: 'Connection timeout (ms)'
      mandatory: true
      type: single
      default: 3000
      visible: true
      validator: '[0-9]+'
      help: The connection timeout to Elasticsearch in milliseconds